### ISSUE TITLE
:hotel: Fix outdated venue information

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/2018.djangocon.us#25] opened 2018-03-09 17:54 UTC
We need to remove all Hotel RL references along with update our 2018 pricing, order links, photos, etc.

**Comment by jefftriplett** [comment] 2018-03-09 18:33
I replaced the photo, updated the reservation link, and crossed off a few more t's.

**Comment by williln** [comment] 2018-03-15 17:00
@jefftriplett Do you know if we have confirmed the accessibility section, specifically: 

- step-free access to all parts of venue, including presentation areas (so we have a ramp available?) 
- Restrooms have stalls with grab bars, but not lowered sinks 
- Service animals have a park nearby where they can be walked 
- hotel doesn't have gender-neutral restrooms 

cc @ossanna16 as Diversity Chair 
 
If we have confirmed those things, then I think this issue can be closed.

**Comment by ossanna16** [comment] 2018-03-15 17:12
Happy to contact the hotel about this if someone can provide me with their contact info. Thank you!

**Comment by KatherineMichel** [comment] 2018-04-25 17:00
Closing because duplicate. See #71

**Closed by KatherineMichel** 2018-04-25 17:00 UTC
Labels: content-needed
